<%@ Page Title="" Language="C#" MasterPageFile="~/View/Master.Master" AutoEventWireup="true" CodeBehind="listarAluno.aspx.cs" Inherits="SisAcad.View.Aluno" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Content" runat="server">
    <!-- Page -->
    <div class="page animsition">
        <div class="page-header">
            <h1 class="page-title">Lista de Alunos</h1>
        </div>
        <div class="page-content container-fluid">
            <!-- Panel Header -->
            <div class="panel">
                <div class="panel-body">
                    <!--<asp:Label ID="lblMat" runat="server" Text="Matricula"></asp:Label>
                    <asp:TextBox ID="tbMat" runat="server"></asp:TextBox> <br />

                    <asp:Label ID="lblNome" runat="server" Text="Nome"></asp:Label>
                    <asp:TextBox ID="tbNome" runat="server"></asp:TextBox>

                    <asp:Label ID="lblCurso" runat="server" Text="Código do Curso"></asp:Label>
                    <asp:TextBox ID="tbCurso" runat="server"></asp:TextBox>-->

                    <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="False" DataSourceID="objAluno">
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id"></asp:BoundField>
                            <asp:BoundField DataField="aluno_Mat" HeaderText="aluno_Mat" SortExpression="aluno_Mat"></asp:BoundField>
                            <asp:BoundField DataField="aluno_Nome" HeaderText="aluno_Nome" SortExpression="aluno_Nome"></asp:BoundField>
                            <asp:BoundField DataField="aluno_TotCred" HeaderText="aluno_TotCred" SortExpression="aluno_TotCred"></asp:BoundField>
                            <asp:BoundField DataField="aluno_DataNasc" HeaderText="aluno_DataNasc" SortExpression="aluno_DataNasc"></asp:BoundField>
                            <asp:BoundField DataField="aluno_MGP" HeaderText="aluno_MGP" SortExpression="aluno_MGP"></asp:BoundField>
                            <asp:BoundField DataField="aluno_CodCurso" HeaderText="aluno_CodCurso" SortExpression="aluno_CodCurso"></asp:BoundField>
                        </Columns>
                    </asp:GridView>
                    <asp:ObjectDataSource runat="server" ID="objAluno" DataObjectTypeName="SisAcad.Model.Aluno" DeleteMethod="Delete" OldValuesParameterFormatString="original_{0}" SelectMethod="Listar" TypeName="SisAcad.Controllers.AlunoController" UpdateMethod="Update">
                    </asp:ObjectDataSource>
                </div>
            </div>
            <!-- End Panel Header -->
        </div>
    </div>
  <!-- End Page -->
</asp:Content>
