//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisAcad.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.wsNewSoap")]
    public interface wsNewSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SisAcad.ServiceReference1.HelloWorldResponse HelloWorld(SisAcad.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SisAcad.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SisAcad.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (soma) of message soma does not match the default value (metodo)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/soma", ReplyAction="*")]
        SisAcad.ServiceReference1.soma1 metodo(SisAcad.ServiceReference1.soma request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/soma", ReplyAction="*")]
        System.Threading.Tasks.Task<SisAcad.ServiceReference1.soma1> metodoAsync(SisAcad.ServiceReference1.soma request);
        
        // CODEGEN: Generating message contract since the wrapper name (sub) of message sub does not match the default value (metodo1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sub", ReplyAction="*")]
        SisAcad.ServiceReference1.sub1 metodo1(SisAcad.ServiceReference1.sub request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sub", ReplyAction="*")]
        System.Threading.Tasks.Task<SisAcad.ServiceReference1.sub1> metodo1Async(SisAcad.ServiceReference1.sub request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SisAcad.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SisAcad.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SisAcad.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SisAcad.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="soma", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class soma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int b;
        
        public soma() {
        }
        
        public soma(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="somaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class soma1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int somaResult;
        
        public soma1() {
        }
        
        public soma1(int somaResult) {
            this.somaResult = somaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sub {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int x;
        
        public sub() {
        }
        
        public sub(int x) {
            this.x = x;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sub1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int subResult;
        
        public sub1() {
        }
        
        public sub1(int subResult) {
            this.subResult = subResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsNewSoapChannel : SisAcad.ServiceReference1.wsNewSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsNewSoapClient : System.ServiceModel.ClientBase<SisAcad.ServiceReference1.wsNewSoap>, SisAcad.ServiceReference1.wsNewSoap {
        
        public wsNewSoapClient() {
        }
        
        public wsNewSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsNewSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsNewSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsNewSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisAcad.ServiceReference1.HelloWorldResponse SisAcad.ServiceReference1.wsNewSoap.HelloWorld(SisAcad.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SisAcad.ServiceReference1.HelloWorldRequest inValue = new SisAcad.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SisAcad.ServiceReference1.HelloWorldRequestBody();
            SisAcad.ServiceReference1.HelloWorldResponse retVal = ((SisAcad.ServiceReference1.wsNewSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisAcad.ServiceReference1.HelloWorldResponse> SisAcad.ServiceReference1.wsNewSoap.HelloWorldAsync(SisAcad.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisAcad.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SisAcad.ServiceReference1.HelloWorldRequest inValue = new SisAcad.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SisAcad.ServiceReference1.HelloWorldRequestBody();
            return ((SisAcad.ServiceReference1.wsNewSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisAcad.ServiceReference1.soma1 SisAcad.ServiceReference1.wsNewSoap.metodo(SisAcad.ServiceReference1.soma request) {
            return base.Channel.metodo(request);
        }
        
        public int metodo(int a, int b) {
            SisAcad.ServiceReference1.soma inValue = new SisAcad.ServiceReference1.soma();
            inValue.a = a;
            inValue.b = b;
            SisAcad.ServiceReference1.soma1 retVal = ((SisAcad.ServiceReference1.wsNewSoap)(this)).metodo(inValue);
            return retVal.somaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisAcad.ServiceReference1.soma1> SisAcad.ServiceReference1.wsNewSoap.metodoAsync(SisAcad.ServiceReference1.soma request) {
            return base.Channel.metodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisAcad.ServiceReference1.soma1> metodoAsync(int a, int b) {
            SisAcad.ServiceReference1.soma inValue = new SisAcad.ServiceReference1.soma();
            inValue.a = a;
            inValue.b = b;
            return ((SisAcad.ServiceReference1.wsNewSoap)(this)).metodoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisAcad.ServiceReference1.sub1 SisAcad.ServiceReference1.wsNewSoap.metodo1(SisAcad.ServiceReference1.sub request) {
            return base.Channel.metodo1(request);
        }
        
        public int metodo1(int x) {
            SisAcad.ServiceReference1.sub inValue = new SisAcad.ServiceReference1.sub();
            inValue.x = x;
            SisAcad.ServiceReference1.sub1 retVal = ((SisAcad.ServiceReference1.wsNewSoap)(this)).metodo1(inValue);
            return retVal.subResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisAcad.ServiceReference1.sub1> SisAcad.ServiceReference1.wsNewSoap.metodo1Async(SisAcad.ServiceReference1.sub request) {
            return base.Channel.metodo1Async(request);
        }
        
        public System.Threading.Tasks.Task<SisAcad.ServiceReference1.sub1> metodo1Async(int x) {
            SisAcad.ServiceReference1.sub inValue = new SisAcad.ServiceReference1.sub();
            inValue.x = x;
            return ((SisAcad.ServiceReference1.wsNewSoap)(this)).metodo1Async(inValue);
        }
    }
}
